format_version: 10
pipelines:
  vault:
    group: Tools
    materials:
      git-b844969:
        git: https://github.com/DevOps-iteration2/observability-tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: "ansible-playbook", arguments: [ "-i", "elk-internal.devopsjourney.fun,", "tools.yml","-e", "tool_name=elk", "-e","ansible_user=ec2-user", "-e", "ansible_password=DevOps321"], run_if: passed}