- name: Download Vault repo
  ansible.builtin.shell: yum install -y yum-utils; yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: latest

- name: Start vault service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: true