- name: Set Name in Prompt
  ansible.builtin.shell: set-prompt prometheus

- name: Prometheus Download
  ansible.builtin.unarchive:
   src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
   dest: /opt
   remote_src: yes
   owner: bin

- name: Copy of Prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus service file
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: yes
